FROM node:24.9.0-alpine3.21

WORKDIR /app

RUN apk add --no-cache curl

RUN addgroup -g 1001 -S react && \
    adduser -S react -u 1001

COPY package*.json ./

RUN npm install

RUN chown -R react:react /app

USER react

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]